# docker-compose.yml
version: "3.9"

services:
  api-user:
    build: ./user
    expose:
      - "8080"
    environment:
      - SERVER_PORT=8080
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - appnet

  api-passagem:
    build: ./passagem
    expose:
      - "8080"
    environment:
      - SERVER_PORT=8080
      - SECRET_KEY=${SECRET_KEY}
      - ADDRESS_RABBITMQ=${ADDRESS_RABBITMQ}
    networks:
      - appnet

  email-service:
    build: ./email
    environment:
      - SERVER_PORT=8080
      - ADDRESS_RABBITMQ=${ADDRESS_RABBITMQ}
      - SECRET_KEY=${SECRET_KEY}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}

    networks:
      - appnet


  nginx:
    image: nginx:1.25-alpine
    container_name: nginx-proxy
    depends_on:
      - api-user
      - api-passagem
      - email-service
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - appnet

networks:
  appnet:
    driver: bridge